### ISSUE TITLE
[bug]: Usernames are defaulting to ouckah

### ISSUE THREAD

**Issue by vanshb03** [Ouckah/pipelines#140]
Under the profiles section, the usernames show up as ouckah as shown in the image.

![image](https://github.com/pipelines-lol/pipelines/assets/48507154/737ece5c-d01f-4bc4-83ef-118c88cd6f95)

**Comment by aidanouckama** [comment]
Haha, unfortunately this is due to an update API request from someone who updated everyone's name to "ouckah". This will be fixed and changeable once we fix usernames 👍
