### ISSUE TITLE
[bug]: inf requests when looking at a profile

### ISSUE THREAD

**Issue by vanshb03** [Ouckah/pipelines#141]
When looking at a profile, {"msg":"No authorization token provided."} tokens keep getting generated indefinitely as shown in the image.

![image](https://github.com/pipelines-lol/pipelines/assets/48507154/07b747dd-cf9f-4dad-98c0-aedbd6a851b8)

**Comment by aidanouckama** [comment]
Thank you @vanshb03! I'm gonna work on a fix for this right now.
