### ISSUE TITLE
Linkedin Scraping

### ISSUE THREAD

**Issue by aidanouckama** [Ouckah/pipelines#34]
Scrape data off linkedin to generate pipelines.
- Maybe have user log into Linkedin, and generate pipeline through that
- If not, web scrape off website

**Comment by C-Nubela** [comment]
Hi there @Ouckah 

I work for Proxycurl, a B2B data provider that extensively scrapes LinkedIn, and we would love to help you with LinkedIn scraping and enrichment.

Our API can be flawlessly built into your existing systems/pipeline.

[You can learn more here](https://nubela.co/proxycurl/linkedin?utm_campaign=content_amplification&utm_source=github&utm_medium=social&utm_content=comments), and feel free to reach out to us at "hello@nubela.co" if you have any questions!
